export const types = {
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    SELECT_QUIZ: 'SELECT_QUIZ',
    CATEGORY_ISLOADED: 'CATEGORY_LOADED',
    CATEGORY_ERROR: 'CATEGORY_ERROR',
    CATEGORY_DATA: 'CATEGORY_DATA',
    ROOT_CATEGORY: 'ROOT_CATEGORY',
}